import type { Meta, StoryObj } from '@storybook/react';
import FacilityCard from './index';
import { getRandomFacilityImage } from '@/utils/facilityImages';

const meta = {
  title: 'Components/Reservation/FacilityCard',
  component: FacilityCard,
  parameters: {
    layout: 'padded',
  },
  tags: ['autodocs'],
  argTypes: {
    facility: {
      description: '체육시설 정보',
    },
    to: {
      description: '링크 경로',
    },
    state: {
      description: '링크 상태',
    },
    style: {
      description: '스타일 속성',
    },
  },
} satisfies Meta<typeof FacilityCard>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {
    facility: {
      id: '1',
      facltCdEncptVl: null,
      refineWgs84Lat: null,
      refineWgs84Logt: null,
      distance: 1200,
      facltDivNm: '체육시설',
      indutypeNm: null,
      facltTypeNm: '체조경기장',
      facltTelno: null,
      sidoNm: '서울특별시',
      signguNm: '송파구',
      refineRoadnmAddr: '서울특별시 송파구 올림픽로 25',
      refineLotnoAddr: '서울특별시 송파구 방이동 88-2',
      siDesc: '서울올림픽공원 체조경기장',
      facltStateNm: null,
      facltHmpgAddr: null,
      facltOpertFormCd: null,
      posesnMainbdNm: null,
      posesnMainbdSidoNm: null,
      posesnMainbdSignguNm: null,
      chrgpsnDeptNm: null,
      facltMangrTelno: null,
      inoutdrDivNm: null,
      audtrmSeatCnt: null,
      audtrmAceptncPsncnt: null,
      facltTotAr: null,
      livelhOpenpublYn: null,
      livelhGymNm: null,
      utlzGrpNm: null,
      facltCreatStdDe: null,
      registStatmntDe: null,
      compltnDe: null,
      suspnbizDe: null,
      clsbizDe: null,
      nationPhstrnFacltYn: null,
      qukprfDesignYn: null,
      selfctrlCheckTargetYn: null,
      registDtm: null,
      updDtm: null,
      refineZipno: null,
      createdAt: '2024-01-01T00:00:00Z',
      updatedAt: '2024-01-01T00:00:00Z',
      imageSrc: null,
      facilityImageBase64: null,
      amenities: [],
      streetViewUrl: null,
      streetViewPreview: null,
    },
    to: '/reservation/facility/1',
  },
};

export const WithImage: Story = {
  args: {
    facility: {
      id: '2',
      facltCdEncptVl: null,
      refineWgs84Lat: null,
      refineWgs84Logt: null,
      distance: 800,
      facltDivNm: '체육시설',
      indutypeNm: null,
      facltTypeNm: '실내체육관',
      facltTelno: null,
      sidoNm: '서울특별시',
      signguNm: '송파구',
      refineRoadnmAddr: '서울특별시 송파구 올림픽로 25',
      refineLotnoAddr: '서울특별시 송파구 방이동 88-2',
      siDesc: '잠실실내체육관',
      facltStateNm: null,
      facltHmpgAddr: null,
      facltOpertFormCd: null,
      posesnMainbdNm: null,
      posesnMainbdSidoNm: null,
      posesnMainbdSignguNm: null,
      chrgpsnDeptNm: null,
      facltMangrTelno: null,
      inoutdrDivNm: null,
      audtrmSeatCnt: null,
      audtrmAceptncPsncnt: null,
      facltTotAr: null,
      livelhOpenpublYn: null,
      livelhGymNm: null,
      utlzGrpNm: null,
      facltCreatStdDe: null,
      registStatmntDe: null,
      compltnDe: null,
      suspnbizDe: null,
      clsbizDe: null,
      nationPhstrnFacltYn: null,
      qukprfDesignYn: null,
      selfctrlCheckTargetYn: null,
      registDtm: null,
      updDtm: null,
      refineZipno: null,
      createdAt: '2024-01-01T00:00:00Z',
      updatedAt: '2024-01-01T00:00:00Z',
      imageSrc: getRandomFacilityImage(),
      facilityImageBase64: null,
      amenities: [],
      streetViewUrl: null,
      streetViewPreview: null,
    },
    to: '/reservation/facility/2',
  },
};

export const LongDistance: Story = {
  args: {
    facility: {
      id: '3',
      facltCdEncptVl: null,
      refineWgs84Lat: null,
      refineWgs84Logt: null,
      distance: 5000,
      facltDivNm: '체육시설',
      indutypeNm: null,
      facltTypeNm: '체육관',
      facltTelno: null,
      sidoNm: '서울특별시',
      signguNm: '강남구',
      refineRoadnmAddr: '서울특별시 강남구 테헤란로 123',
      refineLotnoAddr: '서울특별시 강남구 역삼동 123-45',
      siDesc: '강남구민체육관',
      facltStateNm: null,
      facltHmpgAddr: null,
      facltOpertFormCd: null,
      posesnMainbdNm: null,
      posesnMainbdSidoNm: null,
      posesnMainbdSignguNm: null,
      chrgpsnDeptNm: null,
      facltMangrTelno: null,
      inoutdrDivNm: null,
      audtrmSeatCnt: null,
      audtrmAceptncPsncnt: null,
      facltTotAr: null,
      livelhOpenpublYn: null,
      livelhGymNm: null,
      utlzGrpNm: null,
      facltCreatStdDe: null,
      registStatmntDe: null,
      compltnDe: null,
      suspnbizDe: null,
      clsbizDe: null,
      nationPhstrnFacltYn: null,
      qukprfDesignYn: null,
      selfctrlCheckTargetYn: null,
      registDtm: null,
      updDtm: null,
      refineZipno: null,
      createdAt: '2024-01-01T00:00:00Z',
      updatedAt: '2024-01-01T00:00:00Z',
      imageSrc: null,
      facilityImageBase64: null,
      amenities: [],
      streetViewUrl: null,
      streetViewPreview: null,
    },
    to: '/reservation/facility/3',
  },
};

export const NoDistance: Story = {
  args: {
    facility: {
      id: '4',
      facltCdEncptVl: null,
      refineWgs84Lat: null,
      refineWgs84Logt: null,
      distance: null,
      facltDivNm: '체육시설',
      indutypeNm: null,
      facltTypeNm: '장애인체육관',
      facltTelno: null,
      sidoNm: '서울특별시',
      signguNm: '강서구',
      refineRoadnmAddr: '서울특별시 강서구 마곡동 123',
      refineLotnoAddr: '서울특별시 강서구 마곡동 123-45',
      siDesc: '장애인체육관',
      facltStateNm: null,
      facltHmpgAddr: null,
      facltOpertFormCd: null,
      posesnMainbdNm: null,
      posesnMainbdSidoNm: null,
      posesnMainbdSignguNm: null,
      chrgpsnDeptNm: null,
      facltMangrTelno: null,
      inoutdrDivNm: null,
      audtrmSeatCnt: null,
      audtrmAceptncPsncnt: null,
      facltTotAr: null,
      livelhOpenpublYn: null,
      livelhGymNm: null,
      utlzGrpNm: null,
      facltCreatStdDe: null,
      registStatmntDe: null,
      compltnDe: null,
      suspnbizDe: null,
      clsbizDe: null,
      nationPhstrnFacltYn: null,
      qukprfDesignYn: null,
      selfctrlCheckTargetYn: null,
      registDtm: null,
      updDtm: null,
      refineZipno: null,
      createdAt: '2024-01-01T00:00:00Z',
      updatedAt: '2024-01-01T00:00:00Z',
      imageSrc: null,
      facilityImageBase64: null,
      amenities: [],
      streetViewUrl: null,
      streetViewPreview: null,
    },
    to: '/reservation/facility/4',
  },
};
